name: Build APK from ZIP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Cập nhật lên v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4  # Cập nhật lên v4
      with:
        java-version: '17'

    - name: Unzip project
      run: unzip MyProject.zip -d project

    - name: Copy Gradle files
      run: |
        cp build.gradle project/build.gradle
        cp settings.gradle project/settings.gradle

    - name: Grant execute permission for gradlew
      run: chmod +x project/gradlew

    - name: Build Debug APK
      run: cd project && ./gradlew assembleDebug

    - name: Check APK existence  # Thêm bước kiểm tra file APK
      run: |
        ls -la project/app/build/outputs/apk/debug/
        if [ ! -f "project/app/build/outputs/apk/debug/app-debug.apk" ]; then
          echo "APK file not found!"
          exit 1
        fi

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4  # Cập nhật lên v4
      with:
        name: app-debug.apk
        path: project/app/build/outputs/apk/debug/app-debug.apk
